const seedItems = [
  {
    slug: "food-produce-box",
    title: "Seasonal Produce Box",
    category: "Food",
    type: "Product",
    image:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",
    alt: "Fresh vegetables arranged in a reusable produce box",
    description:
      "A weekly box filled with locally grown vegetables, herbs, and seasonal fruit from urban partner farms.",
    availability: "In stock for weekly pickup",
    price: 24.5,
    location: "Docklands Community Market, Melbourne",
    date: "",
    latitude: -37.814,
    longitude: 144.96332,
    featured: true,
  },
  {
    slug: "food-fermentation-lab",
    title: "Fermentation Lab Workshop",
    category: "Food",
    type: "Workshop",
    image:
      "https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=900&q=80",
    alt: "Glass jars prepared for a fermentation class",
    description:
      "A hands-on workshop where participants learn how to make kimchi, pickled vegetables, and probiotic drinks using low-waste kitchen techniques.",
    availability: "12 seats available",
    price: 35,
    location: "Brunswick Green Kitchen, Melbourne",
    date: "2026-05-11",
    latitude: -37.7667,
    longitude: 144.9626,
    featured: true,
  },
  {
    slug: "food-harvest-market-night",
    title: "Twilight Harvest Market",
    category: "Food",
    type: "Event",
    image:
      "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=900&q=80",
    alt: "People shopping at an evening farmer's market",
    description:
      "An evening event featuring zero-waste food stalls, local growers, and live talks about community-supported agriculture.",
    availability: "Open registration",
    price: 10,
    location: "Queen Victoria Market, Melbourne",
    date: "2026-05-18",
    latitude: -37.8076,
    longitude: 144.9568,
    featured: false,
  },
  {
    slug: "lifestyle-bamboo-starter-kit",
    title: "Bamboo Home Starter Kit",
    category: "Lifestyle",
    type: "Product",
    image:
      "https://images.unsplash.com/photo-1616628182509-c6f3c9f4c60e?auto=format&fit=crop&w=900&q=80",
    alt: "Reusable bamboo home essentials on a wooden table",
    description:
      "A practical set of reusable kitchen and bathroom essentials including bamboo cutlery, soap trays, cloth wipes, and storage jars.",
    availability: "In stock",
    price: 42,
    location: "Urban Harvest Hub Store",
    date: "",
    latitude: -37.8136,
    longitude: 144.9631,
    featured: true,
  },
  {
    slug: "lifestyle-upcycling-studio",
    title: "Upcycling Studio Session",
    category: "Lifestyle",
    type: "Workshop",
    image:
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=900&q=80",
    alt: "Participants creating crafts in an upcycling workshop",
    description:
      "Learn how to turn glass jars, fabric scraps, and old containers into stylish household items that reduce everyday waste.",
    availability: "8 seats available",
    price: 28,
    location: "Fitzroy Makers Studio",
    date: "2026-05-20",
    latitude: -37.7989,
    longitude: 144.978,
    featured: false,
  },
  {
    slug: "lifestyle-repair-cafe",
    title: "Neighbourhood Repair Cafe",
    category: "Lifestyle",
    type: "Event",
    image:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    alt: "Community members repairing small household items together",
    description:
      "A community event where volunteers help repair small appliances, bikes, and household items so they stay out of landfill longer.",
    availability: "Registration open",
    price: 0,
    location: "Carlton Community Hall",
    date: "2026-05-26",
    latitude: -37.8008,
    longitude: 144.9676,
    featured: false,
  },
  {
    slug: "education-balcony-garden-guide",
    title: "Balcony Garden Guide",
    category: "Education",
    type: "Product",
    image:
      "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=900&q=80",
    alt: "Small balcony garden with herbs and leafy greens",
    description:
      "A beginner-friendly illustrated guide that explains how to grow herbs, leafy greens, and pollinator plants in small apartment spaces.",
    availability: "Digital download available",
    price: 12,
    location: "Online resource library",
    date: "",
    latitude: -37.8136,
    longitude: 144.9631,
    featured: false,
  },
  {
    slug: "education-rainwater-workshop",
    title: "Rainwater Reuse Workshop",
    category: "Education",
    type: "Workshop",
    image:
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80",
    alt: "Rainwater barrel beside a garden bed",
    description:
      "A practical session on simple rainwater collection, safe reuse, and water-wise gardening strategies for urban homes and schools.",
    availability: "15 seats available",
    price: 22,
    location: "Southbank Eco Learning Centre",
    date: "2026-06-02",
    latitude: -37.8206,
    longitude: 144.9652,
    featured: true,
  },
  {
    slug: "education-urban-greens-forum",
    title: "Urban Greens Forum",
    category: "Education",
    type: "Event",
    image:
      "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=900&q=80",
    alt: "Audience listening to speakers at a sustainability event",
    description:
      "A public forum with guest speakers discussing rooftop gardens, school sustainability programs, and food resilience in cities.",
    availability: "Open registration",
    price: 15,
    location: "State Library Conference Space, Melbourne",
    date: "2026-06-07",
    latitude: -37.8098,
    longitude: 144.9653,
    featured: false,
  },
];

export default seedItems;